<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms" Version="13.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="GHSA-4g8m-5mj5-c8xg/vulnerable/AuthenticationController.cs" />
    <Compile Include="GHSA-6324-52pr-h4p5/vulnerable/CreatedPackageSchemaRepository.cs" />
    <Compile Include="GHSA-69cg-w8vm-h229/vulnerable/PreviewController.cs" />
    <Compile Include="GHSA-69cg-w8vm-h229/vulnerable/UmbracoViewPage.cs" />
    <Compile Include="GHSA-6ffg-mjg7-585x/vulnerable/CopyDataTypeController.cs" />
    <Compile Include="GHSA-6ffg-mjg7-585x/vulnerable/CreateDataTypeController.cs" />
    <Compile Include="GHSA-6ffg-mjg7-585x/vulnerable/DeleteDataTypeController.cs" />
    <Compile Include="GHSA-6ffg-mjg7-585x/vulnerable/MoveDataTypeController.cs" />
    <Compile Include="GHSA-6ffg-mjg7-585x/vulnerable/UpdateDataTypeController.cs" />
    <Compile Include="GHSA-6xmx-85x3-4cv2/vulnerable/RichTextEditorPastedImages.cs" />
    <Compile Include="GHSA-75vq-qvhr-7ffr/vulnerable/DeliveryApiOutputCachePolicy.cs" />
    <Compile Include="GHSA-77gj-crhp-3gvx/vulnerable/ApplicationBuilderExtensions.cs" />
    <Compile Include="GHSA-8qp8-9rpw-j46c/vulnerable/AuthenticationController.cs" />
    <Compile Include="GHSA-cfr5-7p54-4qg8/vulnerable/AnalyticsController.cs" />
    <Compile Include="GHSA-cfr5-7p54-4qg8/vulnerable/LanguageController.cs" />
    <Compile Include="GHSA-cfr5-7p54-4qg8/vulnerable/PublishedSnapshotCacheStatusController.cs" />
    <Compile Include="GHSA-cfr5-7p54-4qg8/vulnerable/RedirectUrlManagementController.cs" />
    <Compile Include="GHSA-fr6r-p8hv-x3c4/vulnerable/ContentSettingsExtensions.cs" />
    <Compile Include="GHSA-h8wc-r4jh-mg7m/vulnerable/RuntimeState.cs" />
    <Compile Include="GHSA-hfv2-pf68-m33x/vulnerable/ContentTypeController.cs" />
    <Compile Include="GHSA-hfv2-pf68-m33x/vulnerable/DictionaryController.cs" />
    <Compile Include="GHSA-hmg4-wwm5-p999/vulnerable/BackOfficeController.cs" />
    <Compile Include="GHSA-hrww-x3fq-xcvh/vulnerable/BackOfficeAuthPolicyBuilderExtensions.cs" />
    <Compile Include="GHSA-j74q-mv2c-rxmp/vulnerable/PreviewController.cs" />
    <Compile Include="GHSA-pgvc-6h2p-q4f6/vulnerable/AuthenticationController.cs" />
    <Compile Include="GHSA-q62r-8ppj-xvf4/vulnerable/TemporaryFileService.cs" />
    <Compile Include="GHSA-v98m-398x-269r/vulnerable/StylesheetController.cs" />
    <Compile Include="GHSA-wv8v-rmw2-25wc/vulnerable/UmbracoViewPage.cs" />
    <Compile Include="GHSA-wx5h-wqfq-v698/vulnerable/ContentPermissionsQueryStringHandler.cs" />
    <Compile Include="GHSA-wx5h-wqfq-v698/vulnerable/MediaPermissionsQueryStringHandler.cs" />
    <Compile Include="GHSA-xxc6-35r7-796w/vulnerable/RichTextEditorPastedImages.cs" />
    <Compile Include="GHSA-xxc6-35r7-796w/vulnerable/RichTextPropertyEditor.cs" />
  </ItemGroup>
</Project>